# Generated by Django 5.2 on 2025-04-28 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_is_sale_product_sale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='Category',
        ),
    ]
