# Generated by Django 5.2 on 2025-04-28 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_category_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
