# Generated by Django 5.2 on 2025-06-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='Available stock quantity'),
        ),
    ]
