# Generated by Django 3.2.25 on 2025-05-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20250524_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Pay on Delivery'), ('bank_transfer', 'Bank Transfer')], default='cod', max_length=20),
        ),
    ]
